if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

source ~/.aliases
source ~/.bash_completion.d/git

PS1='\[\033[01;32m\]\h:\u\[\033[01;34m\] \w\[\033[01;33m\]$(__git_ps1 " (%s)")
\[\033[01;34m\]\$\[\033[00m\] '


# fixes display of java GUI apps with awesome
if [ "$DISPLAY" ]; then
    wmname LG3D
fi


eval `ssh-agent` > /dev/null
